class ChaptersConstant {
  final List<Map<String, dynamic>> chapters = [
    {'number': 1, 'name': 'Alif Lam Meem', 'arabicName': 'الم', 'pages': 141},
    {'number': 2, 'name': 'Sayaqool', 'arabicName': 'سَيَقُولُ', 'pages': 111},
    {
      'number': 3,
      'name': 'Tilkal Rusul',
      'arabicName': 'تلك الرسل',
      'pages': 120,
    },
    {
      'number': 4,
      'name': 'Lantanalu',
      'arabicName': 'لَنْ تَنَالُوا',
      'pages': 128,
    },
    {
      'number': 5,
      'name': 'Wal Mohsanat',
      'arabicName': 'وَالمُحْصَنَاتُ',
      'pages': 126,
    },
    {
      'number': 6,
      'name': 'Ya Ayyuha',
      'arabicName': 'يَا أَيُّهَا',
      'pages': 110,
    },
    {
      'number': 7,
      'name': 'Wa Iza Samiu',
      'arabicName': 'وَإِذَا سَمِعُوا',
      'pages': 124,
    },
    {
      'number': 8,
      'name': 'Wa Lau Annana',
      'arabicName': 'وَلَوْ أَنَّنَا',
      'pages': 125,
    },
    {
      'number': 9,
      'name': 'Qad Aflaha',
      'arabicName': 'قَدْ أَفْلَحَ',
      'pages': 129,
    },
    {
      'number': 10,
      'name': 'Wa A’lamu',
      'arabicName': 'وَاعْلَمُوا',
      'pages': 122,
    },
    {
      'number': 11,
      'name': 'Ya’taziruna',
      'arabicName': 'يَعْتَذِرُونَ',
      'pages': 127,
    },
    {
      'number': 12,
      'name': 'Wa Mamin Da’abba',
      'arabicName': 'وَمَا مِنْ دَآبَّةٍ',
      'pages': 111,
    },
    {
      'number': 13,
      'name': 'Wa Ma Ubrioo',
      'arabicName': 'وَمَا أُبَرِّئُ',
      'pages': 113,
    },
    {'number': 14, 'name': 'Rubama', 'arabicName': 'رُبَمَا', 'pages': 112},
    {
      'number': 15,
      'name': 'Subhanallazi',
      'arabicName': 'سُبْحَانَ الَّذِي',
      'pages': 127,
    },
    {
      'number': 16,
      'name': 'Qal Alam',
      'arabicName': 'قَالَ أَلَمْ',
      'pages': 130,
    },
    {
      'number': 17,
      'name': 'Aqtarabat',
      'arabicName': 'اقْتَرَبَتْ',
      'pages': 111,
    },
    {
      'number': 18,
      'name': 'Qadd Aflaha',
      'arabicName': 'قَدْ أَفْلَحَ',
      'pages': 120,
    },
    {
      'number': 19,
      'name': 'Wa Qalallazina',
      'arabicName': 'وَقَالَ الَّذِينَ',
      'pages': 115,
    },
    {
      'number': 20,
      'name': 'A’man Khalaq',
      'arabicName': 'أَمَّنْ خَلَقَ',
      'pages': 129,
    },
    {
      'number': 21,
      'name': 'Utlu Ma Oohiya',
      'arabicName': 'اتْلُ مَا أُوحِيَ',
      'pages': 111,
    },
    {
      'number': 22,
      'name': 'Wa Manyaqnut',
      'arabicName': 'وَمَنْ يَقْنُتْ',
      'pages': 130,
    },
    {'number': 23, 'name': 'Wa Mali', 'arabicName': 'وَمَا لِيَ', 'pages': 128},
    {
      'number': 24,
      'name': 'Faman Azlam',
      'arabicName': 'فَمَنْ أَظْلَمُ',
      'pages': 126,
    },
    {
      'number': 25,
      'name': 'Elahe Yuruddu',
      'arabicName': 'إِلَيْهِ يُرَدُّ',
      'pages': 128,
    },
    {'number': 26, 'name': 'Ha’a Meem', 'arabicName': 'حم', 'pages': 121},
    {
      'number': 27,
      'name': 'Qala Fama Khatbukum',
      'arabicName': 'قَالَ فَمَا خَطْبُكُمْ',
      'pages': 122,
    },
    {
      'number': 28,
      'name': 'Qadd Sami Allah',
      'arabicName': 'قَدْ سَمِعَ اللَّهُ',
      'pages': 137,
    },
    {
      'number': 29,
      'name': 'Tabarakallazi',
      'arabicName': 'تَبَارَكَ الَّذِي',
      'pages': 135,
    },
    {
      'number': 30,
      'name': 'Amma Yatasaloon',
      'arabicName': 'عَمَّ يَتَسَاءَلُونَ',
      'pages': 120,
    },
  ];
}